// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzJEiR5xCAGkVCEuXu3OEfebix-YmY_W4',
    appId: '1:11586263062:web:12aa54021985d03f92fd37',
    messagingSenderId: '11586263062',
    projectId: 'cooking-app-1f8ba',
    authDomain: 'cooking-app-1f8ba.firebaseapp.com',
    databaseURL: 'https://cooking-app-1f8ba-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cooking-app-1f8ba.appspot.com',
    measurementId: 'G-FBCWW1V64Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3SAPLfVS-oBPemc0_sjmOSO9qCDS7sBs',
    appId: '1:11586263062:android:3733f838c9c8b9d492fd37',
    messagingSenderId: '11586263062',
    projectId: 'cooking-app-1f8ba',
    databaseURL: 'https://cooking-app-1f8ba-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cooking-app-1f8ba.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzJEiR5xCAGkVCEuXu3OEfebix-YmY_W4',
    appId: '1:11586263062:web:216f97ac6d50cc7e92fd37',
    messagingSenderId: '11586263062',
    projectId: 'cooking-app-1f8ba',
    authDomain: 'cooking-app-1f8ba.firebaseapp.com',
    databaseURL: 'https://cooking-app-1f8ba-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cooking-app-1f8ba.appspot.com',
    measurementId: 'G-XJSNQB9BKG',
  );

}